services:
    web:
        build:
            context: .
            dockerfile: Dockerfile-web
        container_name: web
        ports:
            - "8800:80"
        volumes:
            - ./src:/var/www/html
        depends_on:
            - db
    db:
        build:
            context: .
            dockerfile: Dockerfile-db
        container_name: db
        environment:
            MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
            MYSQL_DATABASE: ${DATABASE}
            MYSQL_USER: ${USER}
            MYSQL_PASSWORD: ${PASSWORD}
        ports:
            - "3706:3306"
        volumes:
            - mysql_data:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8001:80
        environment:
            - PMA_HOST=db
            - PMA_PORT=3306

volumes:
    mysql_data:
        # Define volume for persisting MySQL data
